---
- name: Check BeS-dev-kit Installation
  ansible.builtin.command: bes-dev-kit --version
  register: kit_output
  ignore_errors: true

- name: Install Dependencies
  block: 
    - name: Check installed Python version
      ansible.builtin.command: python3 -c "import sys; print('python_version=' + '.'.join(map(str, sys.version_info[:3])))"
      register: python_version_output
      ignore_errors: true

    - name: Parse Python version
      set_fact:
        installed_python_version: "{{ python_version_output.stdout_lines[0].split('=')[1] }}"
      when: python_version_output.rc == 0

    - name: Upgrade Python to 3.10 if version is below
      become: yes
      become_user: root
      ansible.builtin.command: apt -y update && apt install -y python3.10
      when: python_version_output.rc != 0 or installed_python_version.split('.')[0] | int < 3 or (installed_python_version.split('.')[0] | int == 3 and installed_python_version.split('.')[1] | int < 10)
 
    - name: Check Installed pip version
      ansible.builtin.command: python3 -m pip --version | awk '{print $2}'
      register: pip_version_output
      ignore_errors: true

    - name: Install pip
      become: yes
      become_user: root
      apt:
        name: python3-pip
        state: present
      when: pip_version_output.rc != 0

    - name: Upgrade pip to latest version if needed
      become: yes
      become_user: root
      ansible.builtin.command: pip3 install --upgrade pip
      when: pip_version_output.rc == 0 and pip_version_output.stdout.split('.')[0] | int < 22
  when: kit_output.rc != 0

- name: Install BeS-dev-kit
  become: yes
  become_user: "{{ system_user }}"
  ansible.builtin.command: python3 -m pip install besecure-developer-toolkit
  when: kit_output.rc != 0